# https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

ARG VERSION
FROM ghcr.io/oxcert/netbox:${VERSION}

ARG NETBOX_PATH
COPY ${NETBOX_PATH}/plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install --no-warn-script-location -r /plugin_requirements.txt

COPY plugins-oxcert.py /etc/netbox/config/plugins.py
RUN SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input

