---
# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      upstream:
        required: true
        type: string
      registry:
        required: true
        type: string
      username:
        required: true
        type: string
      image_name:
        required: true
        type: string
      platforms:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: UPSTREAM=${{ inputs.upstream }}
          platforms: ${{ inputs.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: >-
            ${{ inputs.registry }}/${{ inputs.image_name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
